import("//gn/tools.gni")

import("files.gni")

config("app_gui_config") {
  include_dirs = ["include"]
}

component("app_gui") {
  _visibility = true

  sources = app_gui_sources
  deps = [
    "//src/common:common",
    "//src/common_gui:common_gui",
    "//src/workflow:workflow",
    "//src/nd:nd",
    "//src/pvt:pvt",
    ":app_gui_moc"
  ]

  include_dirs = ["src"]

  public_configs = [
    ":app_gui_config"
  ]

  configs = ["//gn:qt_config"]
}

generate_moc("app_gui_moc") {
  sources = app_gui_sources
}
