pvt_sources = [
  "//src/pvt/include/calculators/fluid_experiment.hpp",
  "//src/pvt/include/calculators/water_calculator.hpp",
  "//src/pvt/include/element_status.hpp",
  "//src/pvt/include/fluid_cache.hpp",
  "//src/pvt/include/fluid_experiment_dialog.hpp",
  "//src/pvt/include/fluid_graph.hpp",
  "//src/pvt/include/fluid_props.hpp",
  "//src/pvt/include/fluid_widget.hpp",
  "//src/pvt/include/pvt_manager.hpp",
  "//src/pvt/include/thermal_props.hpp",
  "//src/pvt/include/water_props.hpp",
  "//src/pvt/include/water_props_desc.hpp",
  "//src/pvt/src/calculators/fluid_experiment.cpp",
  "//src/pvt/src/calculators/water_calculator.cpp",
  "//src/pvt/src/fluid_experiment_dialog.cpp",
  "//src/pvt/src/fluid_graph.cpp",
  "//src/pvt/src/fluid_widget.cpp",
  "//src/pvt/src/pvt_manager.cpp",
  "//src/pvt/src/water_props.cpp",
]