objects_data_sources = [
  "//src/nd/objects_data/include/joint_data.hpp",
  "//src/nd/objects_data/include/objects_type.hpp",
  "//src/nd/objects_data/include/object_data.hpp",
  "//src/nd/objects_data/include/object_params.hpp",
  "//src/nd/objects_data/include/object_param_enum.hpp",
  "//src/nd/objects_data/include/pipe_data.hpp",
  "//src/nd/objects_data/include/sink_data.hpp",
  "//src/nd/objects_data/include/source_data.hpp",
  "//src/nd/objects_data/src/joint_data.cpp",
  "//src/nd/objects_data/src/objects_type.cpp",
  "//src/nd/objects_data/src/object_data.cpp",
  "//src/nd/objects_data/src/object_param_enum.cpp",
  "//src/nd/objects_data/src/pipe_data.cpp",
  "//src/nd/objects_data/src/sink_data.cpp",
  "//src/nd/objects_data/src/source_data.cpp",
]