import("//gn/tools.gni")

import("files.gni")

config("reporters_config") {
  include_dirs = ["include"]
}

component("reporters") {
  _visibility = true

  sources = reporters_sources

  deps = [
    "//src/common/base:common_base",
    "//src/common_gui:common_gui",
  ]

  include_dirs = ["src"]

  public_configs = [
    ":reporters_config"
  ]
}