import("files.gni")

config("common_parallel_config") {
  include_dirs = ["include"]
}

component("common_parallel") {
  _visibility = true

  sources = common_parallel_sources

  deps = [
    "//src/common/base:common_base",
    "//src/common/utils:common_utils",
  ]

  include_dirs = ["src"]

  public_configs = [
    ":common_parallel_config"
  ]
}
