import("//gn/tools.gni")

import("files.gni")

config("common_gui_config") {
  include_dirs = ["include"]
}

component("common_gui") {
  _visibility = true

  sources = common_gui_sources
  deps = [
    "//src/common/utils:common_utils",
    ":common_gui_moc"
  ]

  include_dirs = ["src"]

  public_configs = [
    ":common_gui_config",
    "//gn:qt_config"
  ]
}

generate_moc("common_gui_moc") {
  sources = common_gui_sources
}