workflow_sources = [
  "//src/workflow/src/wf_action_treeitem.cpp",
  "//src/workflow/src/workflow.cpp",
  "//src/workflow/src/workflow_dialog.cpp",
  "//src/workflow/src/wf_enums.cpp",
  "//src/workflow/src/wf_action.cpp",
  "//src/workflow/src/wf_action_tree.cpp",
  "//src/workflow/src/wf_action_areaitem.cpp",
  "//src/workflow/src/work_area_tree.cpp",
  "//src/workflow/src/workflow_basic_action/basic_action.cpp",
  "//src/workflow/src/workflow_basic_action/basic_action_storage.cpp",
  "//src/workflow/include/workflow.hpp",
  "//src/workflow/include/wf_enums.hpp",
  "//src/workflow/include/wf_action_areaitem.hpp",
  "//src/workflow/include/wf_action_tree.hpp",
  "//src/workflow/include/workflow_dialog.hpp",
  "//src/workflow/include/wf_action.hpp",
  "//src/workflow/include/work_area_tree.hpp",
  "//src/workflow/include/wf_action_treeitem.hpp",
  "//src/workflow/include/workflow_basic_action/basic_action_storage.hpp",
  "//src/workflow/include/workflow_basic_action/basic_action.hpp",
]