nd_sources = [
  "//src/nd/kernel/phys_q_type.cpp",
  "//src/nd/kernel/phys_q.hpp",
  "//src/nd/kernel/check_network.cpp",
  "//src/nd/kernel/check_network.hpp",
  "//src/nd/kernel/phys_q_type.hpp",
  "//src/nd/kernel/pipe_holder/pipe_calculator.hpp",
  "//src/nd/kernel/pipe_holder/pipe_params.cpp",
  "//src/nd/kernel/pipe_holder/pipe_calculator.cpp",
  "//src/nd/kernel/pipe_holder/pipe_params.hpp",
  "//src/nd/kernel/network_solver/nd_solution.cpp",
  "//src/nd/kernel/network_solver/nd_solver.cpp",
  "//src/nd/kernel/network_solver/nd_solution.hpp",
  "//src/nd/kernel/network_solver/main_equations.hpp",
  "//src/nd/kernel/network_solver/main_equations.cpp",
  "//src/nd/kernel/network_solver/nd_results.hpp",
  "//src/nd/kernel/network_solver/nd_solver.hpp",
  "//src/nd/kernel/network_solver/initial_approximation/initial_approximation_builder.hpp",
  "//src/nd/kernel/network_solver/initial_approximation/rate_initial_approximation.cpp",
  "//src/nd/kernel/network_solver/initial_approximation/pressure_initial_approximation.cpp",
  "//src/nd/kernel/network_solver/initial_approximation/temp_initial_approximation.cpp",
  "//src/nd/kernel/network_solver/matrix_builder/row_element.hpp",
  "//src/nd/kernel/network_solver/matrix_builder/matrix_builder.hpp",
  "//src/nd/kernel/network_solver/matrix_builder/jacobian_row.hpp",
  "//src/nd/kernel/network_solver/equations/nd_pipe_pressure_equation.cpp",
  "//src/nd/kernel/network_solver/equations/nd_source_pressure_equation.hpp",
  "//src/nd/kernel/network_solver/equations/nd_pipe_pressure_equation.hpp",
  "//src/nd/kernel/network_solver/equations/nd_abstract_equation.hpp",
  "//src/nd/kernel/network_solver/equations/nd_equality_pressure_equation.hpp",
  "//src/nd/kernel/network_solver/equations/nd_source_rate_equation.hpp",
  "//src/nd/kernel/network_solver/equations/nd_equality_rate_equation.hpp",
  "//src/nd/kernel/network_solver/equations/nd_joint_rate_equation.hpp",
  "//src/nd/reader/reader.cpp",
  "//src/nd/reader/reader.hpp",
  "//src/nd/reader/settings_reader.cpp",
  "//src/nd/reader/topology_reader.cpp",
  "//src/nd/reader/fluid_reader.cpp",
  "//src/nd/reader/project_reader.cpp",
  "//src/nd/reader/objects_data_reader.hpp",
  "//src/nd/iface/reporter.cpp",
  "//src/nd/iface/events.cpp",
  "//src/nd/iface/async_reporter.h",
  "//src/nd/iface/events.h",
  "//src/nd/iface/topology.cpp",
  "//src/nd/iface/sim_manager.hpp",
  "//src/nd/iface/async_reporter.cpp",
  "//src/nd/iface/nd_manager.cpp",
  "//src/nd/iface/manager.hpp",
  "//src/nd/iface/topology.hpp",
  "//src/nd/iface/reporter.hpp",
  "//src/nd/iface/nd_manager.h",
  "//src/nd/gui/result_widget.cpp",
  "//src/nd/gui/joint_item.cpp",
  "//src/nd/gui/object_tree_item.cpp",
  "//src/nd/gui/pipe_item.hpp",
  "//src/nd/gui/object_dialog.cpp",
  "//src/nd/gui/graph_item.cpp",
  "//src/nd/gui/object_tree.cpp",
  "//src/nd/gui/graph_area.cpp",
  "//src/nd/gui/scene.hpp",
  "//src/nd/gui/pipe_item.cpp",
  "//src/nd/gui/sink_item.hpp",
  "//src/nd/gui/graph_area.hpp",
  "//src/nd/gui/sink_item.cpp",
  "//src/nd/gui/link_item.hpp",
  "//src/nd/gui/source_item.hpp",
  "//src/nd/gui/graph_item.hpp",
  "//src/nd/gui/result_widget.hpp",
  "//src/nd/gui/object_tree_item.hpp",
  "//src/nd/gui/object_tree.hpp",
  "//src/nd/gui/nd_window.cpp",
  "//src/nd/gui/joint_item.hpp",
  "//src/nd/gui/nd_window.hpp",
  "//src/nd/gui/scene.cpp",
  "//src/nd/gui/object_dialog.hpp",
  "//src/nd/gui/source_item.cpp",
  "//src/nd/gui/main_window.hpp",
  "//src/nd/gui/manager_gui/settings_dialog.hpp",
  "//src/nd/gui/manager_gui/save_dialog.hpp",
  "//src/nd/gui/manager_gui/result_tree_item.hpp",
  "//src/nd/gui/manager_gui/create_project_dialog.hpp",
  "//src/nd/gui/manager_gui/result_info_storage.hpp",
  "//src/nd/gui/manager_gui/settings_dialog.cpp",
  "//src/nd/gui/manager_gui/load_dialog.cpp",
  "//src/nd/gui/manager_gui/load_dialog.hpp",
  "//src/nd/gui/manager_gui/create_project_dialog.cpp",
  "//src/nd/gui/manager_gui/save_dialog.cpp",
  "//src/nd/gui/manager_gui/fluid/fluid_list.hpp",
  "//src/nd/gui/manager_gui/fluid/fluid_dialog.hpp",
  "//src/nd/gui/manager_gui/fluid/fluid_dialog.cpp",
  "//src/nd/gui/manager_gui/fluid/fluid_list_item.hpp",
  "//src/nd/gui/manager_gui/fluid/fluid_list.cpp",
  "//src/nd/gui/manager_gui/settings/solver_settings_enum.cpp",
  "//src/nd/gui/manager_gui/settings/solver_settings_enum.hpp",
  "//src/nd/gui/manager_gui/settings/solver_settings_desc.hpp",
  "//src/nd/gui/pipe_project/pipe_project.hpp",
  "//src/nd/gui/pipe_project/pipe_graph.cpp",
  "//src/nd/gui/pipe_project/pipe_graph.hpp",
  "//src/nd/gui/pipe_project/pipe_project.cpp",
  "//src/nd/queue/waitable_request.cpp",
  "//src/nd/queue/thread_class.h",
  "//src/nd/queue/waitable_request.h",
  "//src/nd/queue/thread_class.cpp",
  "//src/nd/tasks/task.cpp",
  "//src/nd/tasks/task.h",
  "//src/nd/tasks/CALCULATE_task.h",
  "//src/nd/tasks/CALCULATE_task.cpp",
  "//src/nd/writer/writer.hpp",
  "//src/nd/writer/writer.cpp",
]